version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"    
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data:Z
  admin:
    image: dpage/pgadmin4
    restart: always
    ports:
    - "5433:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=karolistarasaitis@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
    - pg4_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pg4_data:
    