enum DirectionStatus {
	OPEN = "OPEN",
	OPEN_BUT_TOO_FAR = "OPEN_BUT_TOO_FAR",
	OPEN_TRANSITION_STAGE = "OPEN_TRANSITION_STAGE",
	OPEN_FINAL_STAGE = "OPEN_FINAL_STAGE",
	CLOSED = "CLOSED"
}

export default DirectionStatus;
